sudo: required
dist: bionic

addons:
  apt:
    update: true
    packages:
    - qemu-kvm
    - cpu-checker

install:
  - egrep -c '(vmx|svm)' /proc/cpuinfo
  - lsmod | grep -i kvm

script:
  - kvm-ok
  - sudo kvm-ok
  - wget http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-amd64.img.xz
  - unxz ubuntu-core-18-amd64.img.xz
  - kvm -smp 2 -m 1500 -netdev user,id=mynet0,hostfwd=tcp::8022-:22,hostfwd=tcp::8090-:80 -device virtio-net-pci,netdev=mynet0 -vga qxl -drive file=ubuntu-core-18-amd64.img,format=raw
